
STUDENT_DATA = {
    "Ramith Chaudhary (8-A)": {
        "English": {"Raw": 59, "Total": 60, "Scaled": 800, "Percentile": 99},
        "Science": {"Raw": 40, "Total": 45, "Scaled": 757, "Percentile": 98},
        "Maths": {"Raw": 36, "Total": 40, "Scaled": 752, "Percentile": 98},
        "Social Studies": {"Raw": 34, "Total": 45, "Scaled": 678, "Percentile": 95},
        "Hindi": {"Raw": 34, "Total": 45, "Scaled": 642, "Percentile": 91},
    },
    "Saksham Shiv Singh Pandya (8-B)": {
        "Hindi": {"Raw": 32, "Total": 45, "Scaled": 709, "Percentile": 98},
        "Maths": {"Raw": 30, "Total": 40, "Scaled": 675, "Percentile": 92},
        "English": {"Raw": 47, "Total": 60, "Scaled": 667, "Percentile": 91},
        "Science": {"Raw": 22, "Total": 45, "Scaled": 508, "Percentile": 51},
        "Social Studies": {"Raw": 14, "Total": 45, "Scaled": 431, "Percentile": 28},
    },
    "Arnav Lohiya (8-B)": {
        "Maths": {"Raw": 31, "Total": 40, "Scaled": 656, "Percentile": 90},
        "English": {"Raw": 44, "Total": 60, "Scaled": 626, "Percentile": 83},
        "Hindi": {"Raw": 21, "Total": 45, "Scaled": 564, "Percentile": 75},
        "Social Studies": {"Raw": 19, "Total": 45, "Scaled": 504, "Percentile": 55},
        "Science": {"Raw": 20, "Total": 45, "Scaled": 501, "Percentile": 49},
    },
    "Shahil Akhtar (8-B)": {
        "Hindi": {"Raw": 27, "Total": 45, "Scaled": 630, "Percentile": 89},
        "Maths": {"Raw": 29, "Total": 40, "Scaled": 644, "Percentile": 88},
        "Social Studies": {"Raw": 27, "Total": 45, "Scaled": 556, "Percentile": 72},
        "English": {"Raw": 28, "Total": 60, "Scaled": 497, "Percentile": 45},
        "Science": {"Raw": 21, "Total": 45, "Scaled": 494, "Percentile": 46},
    },
    "Piyush Dixit (8-A)": {
        "English": {"Raw": 51, "Total": 60, "Scaled": 714, "Percentile": 96},
        "Maths": {"Raw": 29, "Total": 40, "Scaled": 662, "Percentile": 91},
        "Science": {"Raw": 29, "Total": 45, "Scaled": 609, "Percentile": 83},
        "Social Studies": {"Raw": 28, "Total": 45, "Scaled": 593, "Percentile": 82},
        "Hindi": {"Raw": 15, "Total": 45, "Scaled": 461, "Percentile": 46},
    },
    "Saquib Reza (8-C)": {
        "Social Studies": {"Raw": 26, "Total": 45, "Scaled": 600, "Percentile": 84},
        "Maths": {"Raw": 23, "Total": 40, "Scaled": 589, "Percentile": 77},
        "Hindi": {"Raw": 23, "Total": 45, "Scaled": 595, "Percentile": 83},
        "English": {"Raw": 37, "Total": 60, "Scaled": 551, "Percentile": 62},
        "Science": {"Raw": 18, "Total": 45, "Scaled": 472, "Percentile": 37},
    },
    "Shreyansh Verma (8-A)": {
        "English": {"Raw": 35, "Total": 60, "Scaled": 546, "Percentile": 61},
        "Hindi": {"Raw": 15, "Total": 45, "Scaled": 500, "Percentile": 59},
        "Social Studies": {"Raw": 17, "Total": 45, "Scaled": 443, "Percentile": 33},
        "Maths": {"Raw": 10, "Total": 40, "Scaled": 418, "Percentile": 17},
        "Science": {"Raw": 7, "Total": 45, "Scaled": 327, "Percentile": 1},
    },
    "Vedaant Jha (8-C)": {
        "English": {"Raw": 40, "Total": 60, "Scaled": 589, "Percentile": 74},
        "Social Studies": {"Raw": 22, "Total": 45, "Scaled": 525, "Percentile": 63},
        "Science": {"Raw": 19, "Total": 45, "Scaled": 480, "Percentile": 40},
        "Maths": {"Raw": 10, "Total": 40, "Scaled": 426, "Percentile": 20},
        "Hindi": {"Raw": 9, "Total": 45, "Scaled": 415, "Percentile": 24},
    },
    "Mohammad Daud (8-C)": {
        "Hindi": {"Raw": 17, "Total": 45, "Scaled": 522, "Percentile": 66},
        "Maths": {"Raw": 16, "Total": 40, "Scaled": 492, "Percentile": 47},
        "Science": {"Raw": 17, "Total": 45, "Scaled": 454, "Percentile": 30},
        "Social Studies": {"Raw": 14, "Total": 45, "Scaled": 427, "Percentile": 27},
        "English": {"Raw": 18, "Total": 60, "Scaled": 396, "Percentile": 12},
    },
    "Bushra Jahan (8-A)": {
        "Hindi": {"Raw": 14, "Total": 45, "Scaled": 498, "Percentile": 58},
        "Science": {"Raw": 20, "Total": 45, "Scaled": 473, "Percentile": 38},
        "Maths": {"Raw": 13, "Total": 40, "Scaled": 459, "Percentile": 33},
        "English": {"Raw": 23, "Total": 60, "Scaled": 453, "Percentile": 30},
        "Social Studies": {"Raw": 16, "Total": 45, "Scaled": 427, "Percentile": 27},
    },
    "Md. Humza Amir Khan (8-B)": {
        "Hindi": {"Raw": 13, "Total": 45, "Scaled": 483, "Percentile": 53},
        "Maths": {"Raw": 16, "Total": 40, "Scaled": 485, "Percentile": 44},
        "Science": {"Raw": 13, "Total": 45, "Scaled": 424, "Percentile": 20},
        "English": {"Raw": 16, "Total": 60, "Scaled": 396, "Percentile": 12},
        "Social Studies": {"Raw": 8, "Total": 45, "Scaled": 335, "Percentile": 2},
    },
    "Das Profile 1 (8-B)": {
        "Social Studies": {"Percentile": 92},
        "English": {"Percentile": 76},
        "Hindi": {"Percentile": 74},
        "Science": {"Percentile": 62},
        "Maths": {"Percentile": 38},
    },
    "Das Profile 2 (8-C)": {
        "English": {"Percentile": 91},
        "Hindi": {"Percentile": 87},
        "Social Studies": {"Percentile": 79},
        "Science": {"Percentile": 45},
        "Maths": {"Percentile": 35},
    },
    "Khan Profile 1 (8-A)": {
        "Hindi": {"Percentile": 97},
        "English": {"Percentile": 82},
        "Social Studies": {"Percentile": 80},
        "Maths": {"Percentile": 84},
        "Science": {"Percentile": 42},
    },
    "Khan Profile 2 (8-B)": {
        "Maths": {"Percentile": 95},
        "Science": {"Percentile": 92},
        "Social Studies": {"Percentile": 40},
        "English": {"Percentile": 12},
        "Hindi": {"Percentile": 26},
    },
    "Kumar Profile 1 (8-C)": {
        "Science": {"Percentile": 62},
        "Hindi": {"Percentile": 79},
        "English": {"Percentile": 67},
        "Social Studies": {"Percentile": 63},
        "Maths": {"Percentile": 26},
    },
    "Kumar Profile 2 (8-C)": {
        "English": {"Percentile": 64},
        "Maths": {"Percentile": 47},
        "Social Studies": {"Percentile": 46},
        "Hindi": {"Percentile": 53},
        "Science": {"Percentile": 27},
    },
    "Sharma Profile 1 (8-B)": {
        "Hindi": {"Percentile": 59},
        "English": {"Percentile": 49},
        "Science": {"Percentile": 47},
        "Maths": {"Percentile": 44},
        "Social Studies": {"Percentile": 15},
    },
    "Sharma Profile 2 (8-C)": {
        "Maths": {"Percentile": 44},
        "Social Studies": {"Percentile": 40},
        "Hindi": {"Percentile": 35},
        "Science": {"Percentile": 27},
        "English": {"Percentile": 16},
    },
    "Gupta Profile 1 (8-A)": {
        "Maths": {"Raw": 25, "Total": 40, "Scaled": 599, "Percentile": 80},
        "Social Studies": {"Raw": 23, "Total": 45, "Scaled": 501, "Percentile": 54},
        "Science": {"Raw": 22, "Total": 45, "Scaled": 514, "Percentile": 53},
        "English": {"Raw": 27, "Total": 60, "Scaled": 466, "Percentile": 35},
        "Hindi": {"Raw": 10, "Total": 45, "Scaled": 434, "Percentile": 34},
    },
    "Gupta Profile 3 (8-B) - Exceptionally Gifted": {
        "English": {"Raw": 52, "Total": 60, "Scaled": 734, "Percentile": 97},
        "Social Studies": {"Raw": 34, "Total": 45, "Scaled": 646, "Percentile": 92},
        "Maths": {"Raw": 31, "Total": 40, "Scaled": 660, "Percentile": 91},
        "Science": {"Raw": 32, "Total": 45, "Scaled": 640, "Percentile": 89},
        "Hindi": {"Raw": 19, "Total": 45, "Scaled": 581, "Percentile": 80},
    },
    "Gupta Profile 4 (8-B)": {
        "Science": {"Raw": 30, "Total": 45, "Scaled": 625, "Percentile": 86},
        "Hindi": {"Raw": 23, "Total": 45, "Scaled": 606, "Percentile": 85},
        "English": {"Raw": 42, "Total": 60, "Scaled": 586, "Percentile": 73},
        "Social Studies": {"Raw": 14, "Total": 45, "Scaled": 431, "Percentile": 28},
        "Maths": {"Raw": 11, "Total": 40, "Scaled": 407, "Percentile": 13},
    },
    "Gupta Profile 5 (8-C)": {
        "Maths": {"Raw": 23, "Total": 40, "Scaled": 580, "Percentile": 75},
        "Hindi": {"Raw": 15, "Total": 45, "Scaled": 473, "Percentile": 50},
        "Social Studies": {"Raw": 18, "Total": 45, "Scaled": 439, "Percentile": 31},
        "Science": {"Raw": 16, "Total": 45, "Scaled": 418, "Percentile": 18},
        "English": {"Raw": 19, "Total": 60, "Scaled": 396, "Percentile": 12},
    },
    "Gupta Profile 6 (8-C)": {
        "English": {"Raw": 46, "Total": 60, "Scaled": 636, "Percentile": 85},
        "Hindi": {"Raw": 16, "Total": 45, "Scaled": 525, "Percentile": 66},
        "Social Studies": {"Raw": 20, "Total": 45, "Scaled": 463, "Percentile": 40},
        "Science": {"Raw": 16, "Total": 45, "Scaled": 444, "Percentile": 27},
        "Maths": {"Raw": 10, "Total": 40, "Scaled": 426, "Percentile": 20},
    },
    "Priyanshu (8-B)": {
        "Hindi": {"Raw": 27, "Total": 45, "Scaled": 656, "Percentile": 94},
        "Maths": {"Raw": 29, "Total": 40, "Scaled": 666, "Percentile": 91},
        "Social Studies": {"Raw": 27, "Total": 45, "Scaled": 556, "Percentile": 72},
        "English": {"Raw": 28, "Total": 60, "Scaled": 497, "Percentile": 45},
        "Science": {"Raw": 20, "Total": 45, "Scaled": 488, "Percentile": 43},
    },
    "Gaurav (8-A)": {
        "English": {"Raw": 41, "Total": 60, "Scaled": 591, "Percentile": 74},
        "Hindi": {"Raw": 19, "Total": 45, "Scaled": 554, "Percentile": 73},
        "Social Studies": {"Raw": 24, "Total": 45, "Scaled": 549, "Percentile": 70},
        "Science": {"Raw": 21, "Total": 45, "Scaled": 520, "Percentile": 56},
        "Maths": {"Raw": 11, "Total": 40, "Scaled": 425, "Percentile": 20},
    },
    "Pratham (8-A)": {
        "Science": {"Raw": 32, "Total": 45, "Scaled": 662, "Percentile": 92},
        "English": {"Raw": 47, "Total": 60, "Scaled": 663, "Percentile": 90},
        "Social Studies": {"Raw": 28, "Total": 45, "Scaled": 568, "Percentile": 75},
        "Hindi": {"Raw": 21, "Total": 45, "Scaled": 542, "Percentile": 71},
        "Maths": {"Raw": 14, "Total": 40, "Scaled": 444, "Percentile": 27},
    },
    "Kiara (8-A)": {
        "English": {"Raw": 51, "Total": 60, "Scaled": 698, "Percentile": 94},
        "Science": {"Raw": 30, "Total": 45, "Scaled": 604, "Percentile": 82},
        "Hindi": {"Raw": 19, "Total": 45, "Scaled": 521, "Percentile": 66},
        "Maths": {"Raw": 19, "Total": 40, "Scaled": 514, "Percentile": 55},
        "Social Studies": {"Raw": 14, "Total": 45, "Scaled": 382, "Percentile": 10},
    },
    "Devanshe (8-C)": {
        "Maths": {"Raw": 32, "Total": 40, "Scaled": 710, "Percentile": 95},
        "English": {"Raw": 34, "Total": 60, "Scaled": 518, "Percentile": 52},
        "Hindi": {"Raw": 16, "Total": 45, "Scaled": 466, "Percentile": 48},
        "Social Studies": {"Raw": 20, "Total": 45, "Scaled": 479, "Percentile": 46},
        "Science": {"Raw": 20, "Total": 45, "Scaled": 487, "Percentile": 43},
    },
    "Janya (8-A)": {
        "English": {"Raw": 50, "Total": 60, "Scaled": 700, "Percentile": 95},
        "Science": {"Raw": 30, "Total": 45, "Scaled": 609, "Percentile": 83},
        "Social Studies": {"Raw": 24, "Total": 45, "Scaled": 524, "Percentile": 63},
        "Hindi": {"Raw": 15, "Total": 45, "Scaled": 500, "Percentile": 59},
        "Maths": {"Raw": 13, "Total": 40, "Scaled": 459, "Percentile": 33},
    }
}
